zfcampus/zf-apigility-admin

- config/module.config.php
- src/InputFilter/ContentNegotiationInputFilter.php
- src/InputFilter/CreateContentNegotiationInputFilter.php
- test/InputFilter/ContentNegotiationInputFilterTest.php
- test/InputFilter/CreateContentNegotiationInputFilterTest.php
- test/Model/ContentNegotiationResourceTest.php
This fix addresses #249 by providing a new input filter used in POST requests
to the content-negotiation API. The new input filter checks for the presence of
a `content_name` value in the payload, and then passes the remaining data on to
the parent content negotiation input filter to validate.
A valid POST payload then looks like:
```JSON
{
"content_name": "Test",
"Zend\View\Model\ViewModel": [
"text/html",
"application/xhtml+xml"
]
}
```
While PATCH payloads remove the `content_name` parameter (as it's part of the URI).
> Fix validation of the content-negotiation API

- src/InputFilter/ContentNegotiationInputFilter.php
- src/InputFilter/CreateContentNegotiationInputFilter.php
- src/InputFilter/Validator/ContentNegotiationSelectorsValidator.php
- src/InputFilter/Validator/IsStringValidator.php
- src/Model/ContentNegotiationResource.php
- test/InputFilter/ContentNegotiationInputFilterTest.php
- test/InputFilter/CreateContentNegotiationInputFilterTest.php
- test/Model/ContentNegotiationResourceTest.php
InputFilters require named inputs. Previously, the CN input filter was attempting to allow setting the following data structure:
```php
[
'view model class name' => [ /* array of mediatypes */ ],
]
```
This was failing, because we did not have inputs named after the view model class names (and really cannot).
The changes in this patch push the view-model/mediatype pairs under a "selectors" key, allowing them to be validated correctly. It does this by moving the validation logic to a validator, and then creating an input that composes that validator. The `content_name` validation was also moved into an `IsString` validator.
Since the input filter now has keys for each of `content_name` and `selectors`, the selectors data is now pulled from the latter.
> Working validation for content negotiation rules

- src/InputFilter/CreateContentNegotiationInputFilter.php
- test/InputFilter/CreateContentNegotiationInputFilterTest.php
Per the topic: selectors should be optional when creating a new content-negotiation selector definition.
> Selectors should be optional for CN creation

- README.md
- config/module.config.php
- src/Controller/AuthorizationController.php
Implemented PATCH as an HTTP method for the authorization service, and
deprecated PUT.
Fixes #246
> [#246] Authorization changes should occur with PATCH

- Module.php
- config/module.config.php
- src/Controller/AuthenticationTypeController.php
- src/Controller/AuthenticationTypeControllerFactory.php
- test/Controller/AuthenticationTypeControllerTest.php
- It should only pull data from DefaultAuthenticationListener; removed
dependency on AuthenticationModel.
- Test setup and expectations should match zf-mvc-auth:
- Ensured that authentication types for old-style authentication
configuration are properly injected.
- Ensured that expectations are part of the data set when testing
old-style authentication.
- Corrected expectations for new-style data as well.
- Created factory class for AuthenticationTypeController, and removed injection
of AuthenticationModel.
> Fixed AuthenticationTypeController

- config/module.config.php
Addresses zfcampus/zf-content-validation#39 by adding metadata for the
renamed filters and validators; the originals were kept as well, for
backwards compatibility.
> Added metadata for renamed filters, validators

- src/Controller/PackageController.php
- test/Controller/PackageControllerTest.php
I noticed when using the packaging feature that it failed, due to the API code being unable to resolve `config/routes.php` when executing `vendor/bin/zfdeploy.php`. The fix is to use the fully-qualified path: `vendor/zfcampus/zf-deploy/bin/zfdeploy.php`.
> Packaging fails due to inability to resolve routing configuration

- src/Model/DoctrineAdapterEntity.php
- src/Model/DoctrineAdapterModel.php
- test/Model/DoctrineAdapterEntityTest.php
- test/Model/DoctrineAdapterModelTest.php
- In the model, test for either 'driverClass' OR ('connectionString' OR 'dbname');
former indicates a configured ORM connection, while latter indicates a
configured ODM connection.
- In the entity, base the `adapter_name` on EITHER
`doctrine.entitymanager` OR `doctrine.documentmanager` based on the
adapter type represented.
> ODM support for doctrine connections

- src/Model/DbAdapterModel.php
This PR fixes issue with empty dsn.
If we pass empty dsn to `/apigility/api/db-adapter` endpoint apigility will create/update config file with empty key `dsn`. This will not work in API. For example, DB Autodiscovering is not working then.
> Empty DSN should not be saved in config file

- composer.json
- src/InputFilter/Authentication/OAuth2InputFilter.php
- test/InputFilter/CreateContentNegotiationInputFilterTest.php
Updates code to fit with input filter expectations from ZF 2.4.6+ and ZF 2.5.3+. In particular:
- `OAuth2InpuFilter`'s `dsn` input is now marked optional, allow empty, validate when empty.
- `OAuth2InpuFilter`'s `database` input is now marked optional, allow empty, validate when empty.
- The `CreateContentNegotiationInputFilter` test case was updated to reflect actual validation messages returned by a required but missing input.
> Fixes failing unit tests due to input filter changes

- composer.json
- src/InputFilter/Authentication/OAuth2InputFilter.php
- test/InputFilter/CreateContentNegotiationInputFilterTest.php
To < 2.7.0, to ensure only hydrators implementing the stdlib hydrator interfaces will work.
This patch also fixes failing tests due to changes in zend-inputfilter.
> Update stdlib version constraints

- README.md
A few changes that I think are important:
* The package has now stable releases. So we should remove the version constraint on the "composer require" call.
* Removed the part about making the changes to `composer.json` manually: having that section on the README requires unnecessary maintenance (it has to be updated with every stable release).
* Running `composer update` to install the recently-required package is a bad idea because it will update all other packages. `composer install` should be used instead. Or `composer update --lock` at the very least.
> Improved Install Instructions

- view/code-connected/rest-resource.phtml
patchList method is included in AbstractResourceListener and can be dispatched. Added this method to rest-resource.phtml so it will be included in the boilerplate Resource class when creating a new service.
> Added patchList method to rest-resource.phtml template

- Module.php
- src/Model/AbstractPluginManagerModel.php
- test/Controller/AuthenticationControllerTest.php
- test/Controller/InputFilterControllerTest.php
- test/Controller/ModuleCreationControllerTest.php
- test/Model/DocumentationModelTest.php
- test/Model/ModulePathSpecTest.php
- test/Model/RpcServiceModelTest.php
This patch updates `Module` to pull entities from `ZF\Hal\Entity` instances using that class's `getModule()` method if it is present, falling back to direct property access otherwise. This allows it to be used with zf-hal 1.4 without emitting deprecation notices - which often caused admin API calls to fail!
A number of test classes also were pulling the composed entity using property access, and were updated; these include the `AuthenticationControllerTest`, `InputFilterControllerTest`, and `ModuleCreationControllerTest`.
Finally, when running tests and CS checks, I discovered the following:
- `DocumentationModelTest` was relying on a test asset from zf-configuration; however, the test directory is now omitted from distribution packages, which makes tests fail. I updated to use a mock …
> Allow forwards-compatibility with zf-hal 1.4

- README.md
- composer.json
- composer.lock
- config/module.config.php
- src/Controller/ApigilityVersionController.php
In order to allow separating the skeleton version from the UI version, we need to be able to report the former to the latter.
zfcampus/zf-apigility-skeleton#130 adds a new constant, `Apigility\VERSION`, which reports the current skeleton version. zfcampus/zf-apigility-admin-ui updates the UI's "About" tab to:
- use `@dev` by default for the version
- attempt to query the apigility-version API exposed by the admin
- if not available, keeps the `@dev` default
- if it returns something unexpected, keeps the `@dev` default
- but otherwise, reports that version
This patch exposes the apigility-version API. It will return the value of `Apigility\VERSION`, if defined, but otherwise return `@dev`.
> Expose the apigility-version API

- README.md
- bin/apigility-upgrade-to-1.5
The default skeleton from previous versions includes translation features in the layout; when development mode is off, these then are executed, and, for those upgrading, lack of i18n causes fatal errors.
This patch makes the following changes to the upgrade script:
- Adds zend-mvc-i18n as an application requirement.
- Injects both `Zend\I18n` and `Zend\Mvc\I18n` as production modules.
Reported by @jackdpeterson in #apigility-dev
> Have upgrade script install zend-mvc-i18n

- README.md
- config/module.config.php
In prepping the Apigility 1.4 skeleton, I discovered that we were not yet documenting the `zf-apigility-admin.path_spec` configuration, which has been available since 1.1.0. This patch adds documentation in the README, as well as the module configuration.
> Document zf-apigility-admin.path_spec configuration

- src/Model/ModuleModel.php
- src/Model/ModuleModelFactory.php
- test/Model/ModuleModelFactoryTest.php
- test/Model/ModuleModelTest.php
Updates generation of the config/modules.config.php file to use short array notation instead of long array notation.
Alternative to #359, as it presents fewer changes.
> Create modules.config.php using short array notation

- src/Model/ModuleModel.php
- test/Model/ModuleModelTest.php
Previously, the ModuleModel would create an empty `config/module.config.php` stub that always defined `return array()` (long array notation). This patch updates the code to vary the return payload based on the short array configuration value.
(Reported in IRC by @webimpress).
> Ensure ModuleModel generates arrays according to configuration

- bin/apigility-upgrade-to-1.5
As of zf-apigility-provider 1.2.0, that package no longer needs to be registered as a module, as all interfaces it defines can and are autoloaded by Composer already.
> Remove ZF\Apigility\Provider from module list

- src/Model/DbAutodiscoveryModel.php
Allow all other exceptions to fall throw.
Fixes #364
Does not conflict with #304
> Suppress only specific database exception

- bin/apigility-upgrade-to-1.5
Now also updates the `public/index.php` to allow using the old style of invoking development mode:
- `php public/index.php development enable`
- `php public/index.php development disable`
These now proxy to the `vendor/bin/zf-development-mode` tooling.
This is done primarily to ensure that invoking the admin in Zend Studio continues to work, as Studio invokes development mode prior to and following launching the admin.
> Added code to migrate legacy development mode commands

- bin/apigility-upgrade-to-1.5
The path needs to use the windows directory separator, and the batch script generated by Composer, when running under windows.
> Vary the path to the development mode script when running under Windows

- .travis.yml
- composer.json
- composer.lock
As noted in https://github.com/zfcampus/zf-configuration/issues/28 seems that [`zfcampus/zf-configuration 1.3.1`](https://github.com/zfcampus/zf-configuration/releases/tag/1.3.1) break Apigility admin.
This PR should prove this - I've updated composer.lock to zf-configuration 1.3.0 so tests will run with the following version of zf-configuration:
- 1.2.1 - lowest :white_check_mark:
- 1.3.0 - locked :white_check_mark:
- 1.3.1 - latest :x:
The change which break Apigility admin at this point was made be me in https://github.com/zfcampus/zf-configuration/pull/25
I think the behaviour of zf-configuration was wrong, the method was not tested and documented, but unfortunately this wrong behaviour has been used in other components.
The simplest solution will be revert change introduced in …
> zfcampus/zf-configuration 1.3.1 - breaks apigility admin

- src/InputFilter/RestService/PostInputFilter.php
On new installs or after updating composer, creating new Rest services fail with the error: 
```
Fatal error: Declaration of ZF\Apigility\Admin\InputFilter\RestService\PostInputFilter::isValid() must be compatible with Zend\InputFilter\BaseInputFilter::isValid($context = NULL) in /var/www/vendor/zfcampus/zf-apigility-admin/src/InputFilter/RestService/PostInputFilter.php on line 12
```
This patch simply adds the new signature so the Rest service can be built.
> Fix for creating new REST services

- src/InputFilter/AuthorizationInputFilter.php
- src/InputFilter/DocumentationInputFilter.php
- src/InputFilter/InputFilterInputFilter.php
I think I got all the filters in this package now and updated the signatures to match.   It appears the compatibility check from interface -> parent -> child got an overhaul in 7.2 and now errors out completely.
with these changes tests for this package now pass in 7.2.
> More filter signature issues

- .travis.yml
- composer.json
- composer.lock
- Updates the zend-hydrator constraint to also allow v3 releases.
- Updates the travis configuration to add zend-hydrator as an alternate dependency for locked environments prior to PHP 7.2.
No code changes were necessary to make this work.
> Allow usage with zend-hydrator v3

- CHANGELOG.md
- src/InputFilter/DocumentationInputFilter.php
- src/Model/DocumentationModel.php
I added this field to be able to personalized methods of the sdks generated with swagger-codegen and zf-apigility-documentation-swagger.
> add operation id to documentation

- src/Controller/PackageController.php
When trying to package APIs on IBM i, there is an issue with the `glob()` method. `glob()` on IBM i needs the full path and not a relative one. To fix this, I use `realpath()` and `basename()`.
> Use realpath to get modules. Fixes packaging on IBM i.
